version: '3.8'

services:
  app:
    container_name: app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
        - postgres
    networks:
        - tasks-net

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    volumes:
        - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - tasks-net

networks:
  tasks-net:
    driver: bridge

volumes:
    postgres-data:
      driver: local
      driver_opts:
        type: none
        device: /home/postgres-data
        o: bind
